apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: webapp-external
spec:
  parentRefs:
    - name: apps-gw
      namespace: apps-gateway
  hostnames:
    - "webapp.apps.kubernetes-okd.digidefence.ktu.edu"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: webapp
          port: 8080
