namespace: webapp

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml

configMapGenerator:
  - name: webapp-config
    literals:
      - MESSAGE=Hello from TestApp via Kubernetes!
      - PORT=8080

images:
  - name: harbor.apps.kubernetes-okd.digidefence.ktu.edu/library/webapp
    newName: harbor.apps.kubernetes-okd.digidefence.ktu.edu/library/webapp
    newTag: 0.1.0
