apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: webapp=harbor.apps.kubernetes-okd.digidefence.ktu.edu/library/webapp
    argocd-image-updater.argoproj.io/webapp.update-strategy: semver
    argocd-image-updater.argoproj.io/write-back-method: kustomize
spec:
  project: default
  source:
    repoURL: https://git.example.com/your/repo.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
